[package]
name = "tachyon3d"
version = "0.0.1-alpha.1"
edition = "2024"
license = "Apache-2.0"
description = "A work in progress engine"

[dependencies]
tachyon3d_internal = { version = "0.0.1-alpha.1", path = "tachyon3d_internal" }
tachyon3d_macros = { version = "0.0.1-alpha.1", path = "tachyon3d_macros" }
tachyon3d_dylib = { version = "0.0.1-alpha.1", path = "tachyon3d_dylib", optional = true }
slotmap = "1.1.1"

[features]
default = []
dynamic_linking = ["dep:tachyon3d_dylib"]

[workspace]
members = ["tachyon3d_dylib","tachyon3d_internal", "tachyon3d_macros"]

resolver = "3"

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }

[[bench]]
name = "scheduler_bench"
harness = false