[package]
name = "tachyon3d"
version = "0.4.23"
edition = "2024"
license = "Apache-2.0"
description = "A work in progress engine"

[dependencies]
tachyon3d_internal = { path = "tachyon3d_internal" }
tachyon3d_proc_macros = { path = "tachyon3d_proc_macros" }
tachyon3d_dylib = { path = "tachyon3d_dylib", optional = true }
slotmap = "1.1.1"

[features]
default = []
dynamic_linking = ["dep:tachyon3d_dylib"]

[workspace]
members = ["tachyon3d_dylib","tachyon3d_internal","tachyon3d_proc_macros"]

resolver = "3"

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }

[[bench]]
name = "scheduler_bench"
harness = false