[package]
name = "tachyon3d_internal"
version = "0.0.1-alpha.1"
edition = "2024"
license = "Apache-2.0"
description = "internal for tachyon3d"




[dependencies]
fxhash = "0.2.1"
corosensei = { version = "0.3.4", optional = true }
crossbeam-deque = { version = "0.8.7" }
slotmap = "1.1.1"
rand = "0.10.2"

